### ISSUE TITLE
Cuda out of memory at inference after finetuning alpaca-lora with 2048 tokens length

### ISSUE THREAD

**Issue by Nikitala0014** [tloen/alpaca-lora#173]
When I finetune alpaca-lora 7b at gpu a10 24gb it's fine, but when I tried to use this trained model in generate script I have got the allocalate memory error. Can you help me understand why I am recieving this error at inference but not at training process?

**Comment by Nikitala0014** [comment]
I resolved this problem by reducing num_beams

**Comment by Jacksonlark** [comment]
> I have resolved this problem by reducing num_beams

I can not find num_beams in the fine-tuning script. Can you give more information?
