### ISSUE TITLE
Encounter issues in distributed finetune training 

### ISSUE THREAD

**Issue by Jeffwan** [tloen/alpaca-lora#188]
This is a follow up issue of my comment here. I would like to leave the record all the logs here.

Environment: 4 * A100 80G on single host.

### 1st try - RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device:  

```
python finetune.py  --base_model '/root/models/llama_7B/'  --data_path './alpaca_data_cleaned.json'  --output_dir './lora-alpaca'

wandb: Tracking run with wandb version 0.14.0
wandb: W&B syncing is set to `offline` in this directory.
wandb: Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
  0%|                                                                                                                                                                                                                                           | 0/291 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/root/alpaca-lora/finetune.py", line 241, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/alpaca-lora/finetune.py", line 210, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1644, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1911, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2657, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2689, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 157, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
wandb: Waiting for W&B process to finish... (failed 1).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /root/alpaca-lora/wandb/offline-run-20230327_170951-4ngzvemg
wandb: Find logs at: ./wandb/offline-run-20230327_170951-4ngzvemg/logs
```

### 2nd try - blocked at `Map` stage. 

I follow https://github.com/tloen/alpaca-lora/issues/8#issuecomment-1477490259 and just a few torch distributed envs and args. but seems it's blocked there. I will definitely follow advice from https://github.com/tloen/alpaca-lora/issues/182#issuecomment-1485729028 and try 2 gpus later. 

```
WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=1234   finetune.py     --base_model '/root/models/llama_7B/'     --data_path './alpaca_data_cleaned.json'     --output_dir './lora-alpaca'
....
....
....

Overriding torch_dtype=None with `torch_dtype=torch.float16` due to requirements of `bitsandbytes` to enable model loading in mixed int8. Either pass torch_dtype=torch.float16 or don't pass this argument at all to remove this warning.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.97s/it]
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 383.85it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-013f535ddf518dde.arrow and /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-cf4d846d5a5d2565.arrow
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.21s/it]
Loading checkpoint shards:  50%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                                     | 1/2 [00:08<00:08,  8.89s/it]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 474.74it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-013f535ddf518dde.arrow and /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-cf4d846d5a5d2565.arrow
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.84s/it]
Map:   5%|█████████▌                                                                                                                                                                                                      | 2283/49942 [00:01<00:38, 1240.75 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 533.63it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-013f535ddf518dde.arrow and /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-cf4d846d5a5d2565.arrow
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.52s/it]
Map:   8%|████████████████▌                                                                                                                                                                                               | 3969/49942 [00:03<00:34, 1333.06 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 470.11it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-013f535ddf518dde.arrow and /root/.cache/huggingface/datasets/json/default-af841b888df60f8e/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-cf4d846d5a5d2565.arrow
```

### 3rd Try - index out of bounds" failed

I notice https://github.com/tloen/alpaca-lora/issues/182#issuecomment-1485195216 sets another env `OMP_NUM_THREADS=4`, I   just give a try. Honestly, I don't know how OpenMPI env plays the role here and I got some weird settings. Not sure whether I should set it to 8 since I am using 4 GPUs but i didn't try 8 earlier. 

```
OMP_NUM_THREADS=4 WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=1234   finetune.py     --base_model '/root/models/llama_7B/'     --data_path './alpaca_data_cleaned.json'     --output_dir './lora-alpaca'
....


../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [120,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [121,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [122,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [123,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [124,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [125,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [126,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
../aten/src/ATen/native/cuda/ScatterGatherKernel.cu:144: operator(): block: [20,0,0], thread: [127,0,0] Assertion idx_dim >= 0 && idx_dim < index_size && "index out of bounds" failed.
Error device-side assert triggered at line 532 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu
```

**Comment by NanoCode012** [comment]
Could you also try set `--micro_batch_size` to be multiple of GPUs? I used https://github.com/tloen/alpaca-lora/issues/8#issuecomment-1477490259 and it was fine on 2.

**Comment by Jeffwan** [comment]
@NanoCode012 Thanks! I tune the parameters and it's working fine now!

```
WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=3192 finetune.py \
    --base_model '/root/llama-7b-hf/' \
    --data_path './alpaca_data_cleaned.json' \
    --output_dir './lora-alpaca' \
    --batch_size 1024 \
    --micro_batch_size 128
```

Here's my complete log, metrics and environments.

- Env: 4*A100-80G
- WandB Report: [Link](https://wandb.ai/jeffwan/alpaca/reports/Alpaca-LoRA-4-A100-80G-Finetune--VmlldzozOTE0Nzgw?accessToken=enuockctssc5fxukc07ndfkj71dur8bl89zervnvmg2vkhw0mwuutvv834gblzge)
- Training logs:
```
root@c35059eec1c7:~/alpaca-lora# WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=3192 finetune.py     --base_model '/root/llama-7b-hf/'     --data_path './alpaca_data_cleaned.json'     --output_dir './lora-alpaca'     --batch_size 1024     --micro_batch_size 128
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/1/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/2/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/0/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
/usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/3/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
Training Alpaca-LoRA model with params:
base_model: /root/llama-7b-hf/
data_path: ./alpaca_data_cleaned.json
output_dir: ./lora-alpaca
batch_size: 1024
micro_batch_size: 128
num_epochs: 3
learning_rate: 0.0003
cutoff_len: 256
val_set_size: 2000
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: False
wandb_project:
wandb_run_name:
wandb_watch:
wandb_log_model:
resume_from_checkpoint: None

Training Alpaca-LoRA model with params:
base_model: /root/llama-7b-hf/
data_path: ./alpaca_data_cleaned.json
output_dir: ./lora-alpaca
batch_size: 1024
micro_batch_size: 128
num_epochs: 3
learning_rate: 0.0003
cutoff_len: 256
val_set_size: 2000
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: False
wandb_project:
wandb_run_name:
wandb_watch:
wandb_log_model:
resume_from_checkpoint: None

Training Alpaca-LoRA model with params:
base_model: /root/llama-7b-hf/
data_path: ./alpaca_data_cleaned.json
output_dir: ./lora-alpaca
batch_size: 1024
micro_batch_size: 128
num_epochs: 3
learning_rate: 0.0003
cutoff_len: 256
val_set_size: 2000
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: False
wandb_project:
wandb_run_name:
wandb_watch:
wandb_log_model:
resume_from_checkpoint: None

Training Alpaca-LoRA model with params:
base_model: /root/llama-7b-hf/
data_path: ./alpaca_data_cleaned.json
output_dir: ./lora-alpaca
batch_size: 1024
micro_batch_size: 128
num_epochs: 3
learning_rate: 0.0003
cutoff_len: 256
val_set_size: 2000
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: True
group_by_length: False
wandb_project:
wandb_run_name:
wandb_watch:
wandb_log_model:
resume_from_checkpoint: None

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.12s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.28s/it]
Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 536.56it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.35s/it]
Map:   1%|█▌                                                                                                                                                                                                   | 389/49759 [00:00<00:38, 1294.21 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 554.80it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
Map:   1%|██                                                                                                                                                                                                   | 523/49759 [00:00<00:37, 1309.32 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 374.96it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.13s/it]
Map:   5%|█████████▉                                                                                                                                                                                          | 2525/49759 [00:01<00:36, 1279.49 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 463.66it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
wandb: Currently logged in as: jeffwan. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in /root/alpaca-lora/wandb/run-20230328_174559-mzmf7gh8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run curious-moon-1
wandb: ⭐️ View project at https://wandb.ai/jeffwan/alpaca
wandb: 🚀 View run at https://wandb.ai/jeffwan/alpaca/runs/mzmf7gh8


{'loss': 2.2763, 'learning_rate': 2.9999999999999997e-05, 'epoch': 0.2}
{'loss': 2.1957, 'learning_rate': 5.9999999999999995e-05, 'epoch': 0.41}
{'loss': 1.9686, 'learning_rate': 8.999999999999999e-05, 'epoch': 0.61}
{'loss': 1.5397, 'learning_rate': 0.00011999999999999999, 'epoch': 0.82}
{'loss': 1.2312, 'learning_rate': 0.00015, 'epoch': 1.02}
{'loss': 1.1251, 'learning_rate': 0.00017999999999999998, 'epoch': 1.22}
{'loss': 0.9606, 'learning_rate': 0.00020999999999999998, 'epoch': 1.43}
{'loss': 0.8537, 'learning_rate': 0.00023999999999999998, 'epoch': 1.63}
{'loss': 0.8412, 'learning_rate': 0.00027, 'epoch': 1.84}
{'loss': 0.838, 'learning_rate': 0.0003, 'epoch': 2.04}
{'loss': 0.8305, 'learning_rate': 0.00023617021276595742, 'epoch': 2.24}
{'loss': 0.8215, 'learning_rate': 0.0001723404255319149, 'epoch': 2.45}
{'loss': 0.8147, 'learning_rate': 0.00010851063829787234, 'epoch': 2.65}
{'loss': 0.8147, 'learning_rate': 4.468085106382978e-05, 'epoch': 2.86}
{'train_runtime': 3187.753, 'train_samples_per_second': 46.828, 'train_steps_per_second': 0.046, 'train_loss': 1.2030427374807344, 'epoch': 3.0}
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147/147 [53:05<00:00, 21.67s/it]

 If there's a warning about missing keys above, please disregard :)

 If there's a warning about missing keys above, please disregard :)

 If there's a warning about missing keys above, please disregard :)

 If there's a warning about missing keys above, please disregard :)
wandb: Waiting for W&B process to finish... (success).
wandb: / 0.015 MB of 0.015 MB uploaded (0.000 MB deduped)
wandb: Run history:
wandb:                    train/epoch ▁▂▂▃▃▄▄▅▅▆▆▇▇██
wandb:              train/global_step ▁▂▂▃▃▄▄▅▅▆▆▇▇██
wandb:            train/learning_rate ▁▂▃▃▄▅▆▆▇█▆▅▃▁
wandb:                     train/loss ██▇▄▃▂▂▁▁▁▁▁▁▁
wandb:               train/total_flos ▁
wandb:               train/train_loss ▁
wandb:            train/train_runtime ▁
wandb: train/train_samples_per_second ▁
wandb:   train/train_steps_per_second ▁
wandb:
wandb: Run summary:
wandb:                    train/epoch 3.0
wandb:              train/global_step 147
wandb:            train/learning_rate 4e-05
wandb:                     train/loss 0.8147
wandb:               train/total_flos 1.5159002374476923e+18
wandb:               train/train_loss 1.20304
wandb:            train/train_runtime 3187.753
wandb: train/train_samples_per_second 46.828
wandb:   train/train_steps_per_second 0.046
wandb:
wandb: 🚀 View run curious-moon-1 at: https://wandb.ai/jeffwan/alpaca/runs/mzmf7gh8
wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230328_174559-mzmf7gh8/logs

```

**Comment by kasakh** [comment]
@Jeffwan I followed this thread and used the command 
```
WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=3192 finetune.py \
    --base_model '/root/llama-7b-hf/' \
    --data_path './alpaca_data_cleaned.json' \
    --output_dir './lora-alpaca' \
    --batch_size 1024 \
    --micro_batch_size 128
```
for finetuning. After finetuning is completed, it stores the adapter files in the `lora-alpaca` directory. For inference, I am using the command 
`python generate.py     --load_8bit     --base_model 'decapoda-research/llama-7b-hf'     --lora_weights "./lora-alpaca" `, the gradia interface opens but no matter what prompt/instruction I give, there is no output being displayed. Can you please share the inference command you used for your case?

**Comment by scarydemon2** [comment]
> @NanoCode012 Thanks! I tune the parameters and it's working fine now!
> 
> ```
> WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=3192 finetune.py \
>     --base_model '/root/llama-7b-hf/' \
>     --data_path './alpaca_data_cleaned.json' \
>     --output_dir './lora-alpaca' \
>     --batch_size 1024 \
>     --micro_batch_size 128
> ```
> 
> Here's my complete log, metrics and environments.
> 
> * Env: 4*A100-80G
> * WandB Report: [Link](https://wandb.ai/jeffwan/alpaca/reports/Alpaca-LoRA-4-A100-80G-Finetune--VmlldzozOTE0Nzgw?accessToken=enuockctssc5fxukc07ndfkj71dur8bl89zervnvmg2vkhw0mwuutvv834gblzge)
> * Training logs:
> 
> ```
> root@c35059eec1c7:~/alpaca-lora# WORLD_SIZE=4 CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 --master_port=3192 finetune.py     --base_model '/root/llama-7b-hf/'     --data_path './alpaca_data_cleaned.json'     --output_dir './lora-alpaca'     --batch_size 1024     --micro_batch_size 128
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> *****************************************
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/1/error.json')}
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 116
> CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/2/error.json')}
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 116
> CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/0/error.json')}
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 116
> CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
> /usr/local/lib/python3.10/dist-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic__vgbqj6n/none_m7wuat9y/attempt_0/3/error.json')}
>   warn(msg)
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 116
> CUDA SETUP: Loading binary /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda116.so...
> Training Alpaca-LoRA model with params:
> base_model: /root/llama-7b-hf/
> data_path: ./alpaca_data_cleaned.json
> output_dir: ./lora-alpaca
> batch_size: 1024
> micro_batch_size: 128
> num_epochs: 3
> learning_rate: 0.0003
> cutoff_len: 256
> val_set_size: 2000
> lora_r: 8
> lora_alpha: 16
> lora_dropout: 0.05
> lora_target_modules: ['q_proj', 'v_proj']
> train_on_inputs: True
> group_by_length: False
> wandb_project:
> wandb_run_name:
> wandb_watch:
> wandb_log_model:
> resume_from_checkpoint: None
> 
> Training Alpaca-LoRA model with params:
> base_model: /root/llama-7b-hf/
> data_path: ./alpaca_data_cleaned.json
> output_dir: ./lora-alpaca
> batch_size: 1024
> micro_batch_size: 128
> num_epochs: 3
> learning_rate: 0.0003
> cutoff_len: 256
> val_set_size: 2000
> lora_r: 8
> lora_alpha: 16
> lora_dropout: 0.05
> lora_target_modules: ['q_proj', 'v_proj']
> train_on_inputs: True
> group_by_length: False
> wandb_project:
> wandb_run_name:
> wandb_watch:
> wandb_log_model:
> resume_from_checkpoint: None
> 
> Training Alpaca-LoRA model with params:
> base_model: /root/llama-7b-hf/
> data_path: ./alpaca_data_cleaned.json
> output_dir: ./lora-alpaca
> batch_size: 1024
> micro_batch_size: 128
> num_epochs: 3
> learning_rate: 0.0003
> cutoff_len: 256
> val_set_size: 2000
> lora_r: 8
> lora_alpha: 16
> lora_dropout: 0.05
> lora_target_modules: ['q_proj', 'v_proj']
> train_on_inputs: True
> group_by_length: False
> wandb_project:
> wandb_run_name:
> wandb_watch:
> wandb_log_model:
> resume_from_checkpoint: None
> 
> Training Alpaca-LoRA model with params:
> base_model: /root/llama-7b-hf/
> data_path: ./alpaca_data_cleaned.json
> output_dir: ./lora-alpaca
> batch_size: 1024
> micro_batch_size: 128
> num_epochs: 3
> learning_rate: 0.0003
> cutoff_len: 256
> val_set_size: 2000
> lora_r: 8
> lora_alpha: 16
> lora_dropout: 0.05
> lora_target_modules: ['q_proj', 'v_proj']
> train_on_inputs: True
> group_by_length: False
> wandb_project:
> wandb_run_name:
> wandb_watch:
> wandb_log_model:
> resume_from_checkpoint: None
> 
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.12s/it]
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.28s/it]
> Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 536.56it/s]
> trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
> Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.35s/it]
> Map:   1%|█▌                                                                                                                                                                                                   | 389/49759 [00:00<00:38, 1294.21 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 554.80it/s]
> trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
> Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
> Map:   1%|██                                                                                                                                                                                                   | 523/49759 [00:00<00:37, 1309.32 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 374.96it/s]
> trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
> Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.13s/it]
> Map:   5%|█████████▉                                                                                                                                                                                          | 2525/49759 [00:01<00:36, 1279.49 examples/s]Found cached dataset json (/root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 463.66it/s]
> trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
> Loading cached split indices for dataset at /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-014b126db45d32ac.arrow and /root/.cache/huggingface/datasets/json/default-089f33be67988669/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-24bb91d28b1fd433.arrow
> wandb: Currently logged in as: jeffwan. Use `wandb login --relogin` to force relogin
> wandb: Tracking run with wandb version 0.14.0
> wandb: Run data is saved locally in /root/alpaca-lora/wandb/run-20230328_174559-mzmf7gh8
> wandb: Run `wandb offline` to turn off syncing.
> wandb: Syncing run curious-moon-1
> wandb: ⭐️ View project at https://wandb.ai/jeffwan/alpaca
> wandb: 🚀 View run at https://wandb.ai/jeffwan/alpaca/runs/mzmf7gh8
> 
> 
> {'loss': 2.2763, 'learning_rate': 2.9999999999999997e-05, 'epoch': 0.2}
> {'loss': 2.1957, 'learning_rate': 5.9999999999999995e-05, 'epoch': 0.41}
> {'loss': 1.9686, 'learning_rate': 8.999999999999999e-05, 'epoch': 0.61}
> {'loss': 1.5397, 'learning_rate': 0.00011999999999999999, 'epoch': 0.82}
> {'loss': 1.2312, 'learning_rate': 0.00015, 'epoch': 1.02}
> {'loss': 1.1251, 'learning_rate': 0.00017999999999999998, 'epoch': 1.22}
> {'loss': 0.9606, 'learning_rate': 0.00020999999999999998, 'epoch': 1.43}
> {'loss': 0.8537, 'learning_rate': 0.00023999999999999998, 'epoch': 1.63}
> {'loss': 0.8412, 'learning_rate': 0.00027, 'epoch': 1.84}
> {'loss': 0.838, 'learning_rate': 0.0003, 'epoch': 2.04}
> {'loss': 0.8305, 'learning_rate': 0.00023617021276595742, 'epoch': 2.24}
> {'loss': 0.8215, 'learning_rate': 0.0001723404255319149, 'epoch': 2.45}
> {'loss': 0.8147, 'learning_rate': 0.00010851063829787234, 'epoch': 2.65}
> {'loss': 0.8147, 'learning_rate': 4.468085106382978e-05, 'epoch': 2.86}
> {'train_runtime': 3187.753, 'train_samples_per_second': 46.828, 'train_steps_per_second': 0.046, 'train_loss': 1.2030427374807344, 'epoch': 3.0}
> 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147/147 [53:05<00:00, 21.67s/it]
> 
>  If there's a warning about missing keys above, please disregard :)
> 
>  If there's a warning about missing keys above, please disregard :)
> 
>  If there's a warning about missing keys above, please disregard :)
> 
>  If there's a warning about missing keys above, please disregard :)
> wandb: Waiting for W&B process to finish... (success).
> wandb: / 0.015 MB of 0.015 MB uploaded (0.000 MB deduped)
> wandb: Run history:
> wandb:                    train/epoch ▁▂▂▃▃▄▄▅▅▆▆▇▇██
> wandb:              train/global_step ▁▂▂▃▃▄▄▅▅▆▆▇▇██
> wandb:            train/learning_rate ▁▂▃▃▄▅▆▆▇█▆▅▃▁
> wandb:                     train/loss ██▇▄▃▂▂▁▁▁▁▁▁▁
> wandb:               train/total_flos ▁
> wandb:               train/train_loss ▁
> wandb:            train/train_runtime ▁
> wandb: train/train_samples_per_second ▁
> wandb:   train/train_steps_per_second ▁
> wandb:
> wandb: Run summary:
> wandb:                    train/epoch 3.0
> wandb:              train/global_step 147
> wandb:            train/learning_rate 4e-05
> wandb:                     train/loss 0.8147
> wandb:               train/total_flos 1.5159002374476923e+18
> wandb:               train/train_loss 1.20304
> wandb:            train/train_runtime 3187.753
> wandb: train/train_samples_per_second 46.828
> wandb:   train/train_steps_per_second 0.046
> wandb:
> wandb: 🚀 View run curious-moon-1 at: https://wandb.ai/jeffwan/alpaca/runs/mzmf7gh8
> wandb: Synced 5 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
> wandb: Find logs at: ./wandb/run-20230328_174559-mzmf7gh8/logs
> ```

Great! It's work for me

**Comment by Jeffwan** [comment]
>  Can you please share the inference command you used for your case?

@kasakh here's the command and output of my inference code. I can only find the logs using hugging face lora weights. I see you did replace lora weights with yours. Please give `tloen/alpaca-lora-7b` a try. I will also double test my personal weights and share with you the result

```
python generate.py --load_8bit --base_model '/home/ubuntu/models/llama_7B/' --lora_weights 'tloen/alpaca-lora-7b'

CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(msg)
/home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ubuntu/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.98s/it]
Downloading (…)/adapter_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 370/370 [00:00<00:00, 86.8kB/s]
Downloading adapter_model.bin: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16.8M/16.8M [00:00<00:00, 101MB/s]
/home/ubuntu/.local/lib/python3.8/site-packages/gradio/inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/ubuntu/.local/lib/python3.8/site-packages/gradio/deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```
