### ISSUE TITLE
Can't train the original llama-7b model on a 3090

### ISSUE THREAD

**Issue by oceanplexian** [tloen/alpaca-lora#236]
Hello 👋  I'm playing around with alpaca-lora. 

I ran into a couple of stumbling blocks. The training instructions list `llama-7b-hf` in the example arguments but that model won't train on a 24Gb GPU without throwing an OOM error. e.g. 
```
python finetune.py --base-model ../models/llama-7b-hf --data_path ../alpaca-cleaned/alpaca_data_cleaned.json --output_dir ../models/lora-alpaca
...
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
```

I was able to get training to work with this fork (https://github.com/johnsmith0031/alpaca_lora_4bit) using `llama-7b-hf-int4` w/ 64Gb of RAM and 24Gb of VRAM on Ubuntu 22.04.

**Comment by AngainorDev** [comment]
I'm training 7b and 13b on 3090.
This repo is supposed to load the models with 8bits, so 13B model = 13GB vram on the GPU.

Your error seems to point to the model being loaded in 32 bits instead of 8bits.
Unless you changed the related code, this could point to something related to the "bitsandbytes" module.

**Comment by tloen** [comment]
I've actually noticed this problem with the most recent version of the code on my 4090. Debugging now.

**Comment by diegomontoya** [comment]
@tloen  Is this similar to the issue where multi-gpu on 4090/3090 are getting stuck? pytorch 2.0 cuda 11.8

https://github.com/tloen/alpaca-lora/issues/250

**Comment by Asteroid77** [comment]
I think it may cause for the version of pytorch is incorrect according to my friend said.
I had same problem before, and solve it now.
the version of torch;torchvision;torchaudio should be supported by CUDA, and its final version is like: 
exec `pip list` :
```bash
....
torch                         2.0.0+cu118
torchaudio                    2.0.1+cu118
torchvision                   0.15.1+cu118
```
and then you may also need this: https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/

I hope I can help you :)

**Comment by sifei** [comment]
Agree with @Asteroid77 
I run the  ```pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118``` to install the torch to solved my issue
