### ISSUE TITLE
RuntimeError: Expected to mark a variable ready only once. 

### ISSUE THREAD

**Issue by candowu** [tloen/alpaca-lora#301]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /data/candowu/miniconda3/envs/llama did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.7/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Training Alpaca-LoRA model with params:
base_model: decapoda-research/llama-7b-hf
data_path: ./alpaca_data_cleaned_archive.json
output_dir: ./alpaca_data_cleaned_archive
batch_size: 128
micro_batch_size: 2
num_epochs: 1
learning_rate: 0.0003
cutoff_len: 512
val_set_size: 50
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: ['q_proj', 'v_proj']
train_on_inputs: False
group_by_length: False
wandb_project: 
wandb_run_name: 
wandb_watch: 
wandb_log_model: 
resume_from_checkpoint: False
prompt template: alpaca

  0%|          | 0/403 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data/candowu/alpaca-lora-main/finetune.py", line 276, in <module>
    fire.Fire(train)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/candowu/alpaca-lora-main/finetune.py", line 266, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py", line 2709, in training_step
    self.scaler.scale(loss).backward()
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
Parameter at index 127 has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.

  0%|          | 0/403 [01:39<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 127891) of binary: /data/candowu/miniconda3/envs/llama/bin/python
Traceback (most recent call last):
  File "/data/candowu/miniconda3/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/candowu/miniconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-09_20:26:15
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 127891)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:09.0 Off |                    0 |
| N/A   43C    P8    15W /  70W |      2MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by ElleLeonne** [comment]
`Expected to mark a variable ready only once. This error is caused by one of the following reasons:

1) Use of a module parameter outside the forward function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.

2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple checkpoint functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.

Parameter at index 127 has been marked as ready twice. This means that multiple autograd engine hooks have fired for this particular parameter during this iteration. You can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print parameter names for further debugging.`

Your code is either having issues when running ddp (distributed data parallelization), or you have multiple forward/backward passes in your model object (unlikely, if you're just running the base finetune script).

I'm guessing it's more likely that you have multiple GPU's, in which case I'd suggest running the script using torchrun instead.
ex
`WORLD_SIZE=2 CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node=2 --master_port=1234 finetune.py`
for two GPU's

**Comment by candowu** [comment]
only one gpu，here is command i used 

WANDB_MODE=disabled nohup torchrun finetune.py --base_model='decapoda-research/llama-7b-hf' --num_epochs=1 --cutoff_len=512 --output_dir='./alpaca_data_cleaned_archive' --micro_batch_size=2 --data_path './alpaca_data_cleaned_archive.json' --val_set_size 200 --train_on_inputs True 2>&1 > alpaca_data_cleaned_archive.log &

**Comment by candowu** [comment]
WANDB_MODE=disabled CUDA_VISIBLE_DEVICES=0 nohup python finetune.py --base_model='decapoda-research/llama-7b-hf' --num_epochs=1 --cutoff_len=512 --output_dir='./alpaca_data_cleaned_archive' --micro_batch_size=2 --data_path='./alpaca_data_cleaned_archive.json' --val_set_size=200 --train_on_inputs=True 2>&1 > alpaca_data_cleaned_archive.log &

**Comment by ElleLeonne** [comment]
> this command works!
> 
> WANDB_MODE=disabled CUDA_VISIBLE_DEVICES=0 nohup python finetune.py --base_model='decapoda-research/llama-7b-hf' --num_epochs=1 --cutoff_len=512 --output_dir='./alpaca_data_cleaned_archive' --micro_batch_size=2 --data_path='./alpaca_data_cleaned_archive.json' --val_set_size=200 --train_on_inputs=True 2>&1 > alpaca_data_cleaned_archive.log &

Interesting, so you only had one GPU, but the command for forcing your system to only see one GPU was what worked. Good to know

**Comment by TomasAndersonFang** [comment]
Hi,

I met the same problem when fine-tuning llama on multiple GPUs. And I used TORCH_DISTRIBUTED_DEBUG=DETAIL to debug, and it returned the following result: 
```
Parameter at index 127 with name base_model.model.model.layers.31.self_attn.v_proj.lora_B.default.weight has been marked as ready twice.
```
So It seems Lora target modules are ready twice, but I don't know how to fix it.

Extra information: If I used one GPU, everything would be ok. If I took full-params fine-tuning, everything would be ok. So I guess this may be a bug.

**Comment by ElleLeonne** [comment]
Are you using multiple DDP methods?

That could be one reason why a Module might be getting instantiated twice.

**Comment by TomasAndersonFang** [comment]
> Are you using multiple DDP methods?
> 
> That could be one reason why a Module might be getting instantiated twice.

I use Accelerate to perform DDP with the command `accelerate launch *.py`. I don't know whether I use multiple DDP. So how to make sure of it?

**Comment by ElleLeonne** [comment]
If you're using the default repo, I know there's some ddp code in there. You'd have to play around, it's been a few months on my end.

I was using torchrun and it worked fine, so it might be torch ddp conflicting with accelerate

**Comment by TomasAndersonFang** [comment]
> 
Actually I only use your code to set Lora for llama, and I didn't add any ddp code.

**Comment by TomasAndersonFang** [comment]
> 

I fixed my problem by setting `--ddp_find_unused_parameters=False`.

**Comment by liuchengyuan123** [comment]
> > 
> 
> I fixed my problem by setting `--ddp_find_unused_parameters=False`.

This really helps, thanks!!

**Comment by francisco-becker** [comment]
@TomasAndersonFang this fixed the issue I was having as well. Thank you!!
