### ISSUE TITLE
Cuda OOM when fine-tuning 13B

### ISSUE THREAD

**Issue by flyman3046** [tloen/alpaca-lora#344]
I was able to fine-tune 7B model with one A100-40G GPU but ran into OOM when fine-tuning 13B. 

Here is the error message:

```
│ /opt/conda/lib/python3.7/site-packages/bitsandbytes/nn/modules.py:268 in _save_to_state_dict     │
│                                                                                                  │
│   265 │   │                                                                                      │
│   266 │   │   try:                                                                               │
│   267 │   │   │   if reorder_layout:                                                             │
│ ❱ 268 │   │   │   │   self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)    │
│   269 │   │   │                                                                                  │
│   270 │   │   │   super()._save_to_state_dict(destination, prefix, keep_vars)                    │
│   271                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.7/site-packages/bitsandbytes/autograd/_functions.py:100 in undo_layout    │
│                                                                                                  │
│    97 │   outputs[tile_indices.flatten()] = tensor                                               │
│    98 │   outputs = outputs.reshape(tile_rows, tile_cols, cols // tile_cols, rows // tile_rows   │
│    99 │   outputs = outputs.permute(3, 0, 2, 1)  # (rows // tile_rows, tile_rows), (cols // ti   │
│ ❱ 100 │   return outputs.reshape(rows, cols).contiguous()                                        │
│   101                                                                                            │
│   102                                                                                            │
│   103 class MatMul8bit(torch.autograd.Function):                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 68.00 MiB (GPU 0; 39.41 GiB total capacity; 35.83 GiB already allocated; 34.50 MiB free; 38.17 GiB reserved in
total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF
```

My command is:
```
python finetune.py \
    --base_model='decapoda-research/llama-13b-hf' \
    --num_epochs=5 \
    --cutoff_len=512 \
    --group_by_length \
    --output_dir='./alpaca-lora-saved-model-13b' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
    --lora_r=16 \
    --micro_batch_size=8
```
I tried a couple of times, e.g., with a smaller `cutoff_len` but still got the same OOM error. One thing I noticed is that the issue happened after training ~10% steps. Any thoughts or help is greatly appreciated.

**Comment by lksysML** [comment]
Running into the same issue. Getting OOM after 7-10% while running on 4x A100-40GB.

Started at --micro_batch_size=24 and have been reducing it till 8 and it still OOMs at around 10%

Running with 

```
CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nproc_per_node=4 torchrun finetune.py \
    --base_model="yahma/llama-13b-hf" \
    --num_epochs=5 \
    --cutoff_len=512 \
    --output_dir='./alpaca-lora-saved-model-13b' \
    --lora_target_modules='[q_proj,k_proj,v_proj,o_proj]' \
    --lora_r=16 \
    --micro_batch_size=8
```

Any ideas?

**Comment by flyman3046** [comment]
I retrained 7b without any issues. For 13B, I tried a couple of things but to no avail:
1. Use a smaller `cutoff_len = 256`
2. Use a smaller `batch_size = 64`

Here is the wandb link to a job: https://wandb.ai/zhengfei-hit/huggingface/runs/6mt3ilc0/overview?workspace=user-zhengfei-hit.

The job used only 45% GPU memory before OOM.

**Comment by lksysML** [comment]
Tried setting max_split_size_mb to 128mb and 64mb. Still didn't help, errors out at 10% when I think it is checkpointing or something

**Comment by lksysML** [comment]
Yes

> I retrained 7b without any issues. For 13B, I tried a couple of things but to no avail:
> 
>     1. Use a smaller `cutoff_len = 256`
> 
>     2. Use a smaller `batch_size = 64`
> 
> 
> Here is the wandb link to a job: https://wandb.ai/zhengfei-hit/huggingface/runs/6mt3ilc0/overview?workspace=user-zhengfei-hit.
> 
> The job used only 45% GPU memory before OOM.

It errored out at 10% after doing a checkpoint? (I think)

**Comment by lksysML** [comment]
Usually errors out when it reaches 200 iterations.
@tloen What do you think?

I rented 8x RTX 3090 and getting same issue there. At 10% or 200 iterations it errors out

**Comment by lksysML** [comment]
I was able to fix this issue by rolling back accelerate, peft, bitsandbytes and transformers to a commit dated around 5-6 april when my previous finetunes were successful. Didn't change any parameters and everything worked. 

It's definitely an issue with one of these dependencies, need to pin point which one.

**Comment by SerCeMan** [comment]
Thank you, fixing the version of `bitsandbytes` to 0.37.2 resolved the issue for me.
```
bitsandbytes==0.37.2
```

**Comment by flyman3046** [comment]
Thanks @SerCeMan. Setting `bitsandbytes==0.37.2` works for me. So closed it.

**Comment by SerCeMan** [comment]
Hey, @flyman3046! It might be worth keeping the issue open so that others who are likely to face the OOM issues can see it.

**Comment by flyman3046** [comment]
@SerCeMan SG, re-opened it until the issue from `bitsandbytes` is fixed.

**Comment by guihonghao** [comment]
> Thank you, fixing the version of `bitsandbytes` to 0.37.2 resolved the issue for me. ([TimDettmers/bitsandbytes#324](https://github.com/TimDettmers/bitsandbytes/issues/324))
> 
> ```
> bitsandbytes==0.37.2
> ```

Yes, I meet an OOM when fine-tuning 13B on 2 * 3090 24GB. It seems happening while saving model.state_dict. And i solved it by `pip bitsandbytes==0.37.2`(My bitsandbytes version is 0.38.2, before)

**Comment by teknium1** [comment]
> 

Im on 0.37.2 and it still occurrs.

**Comment by jonataslaw** [comment]
I can confirm, upgrading bitsandbytes to  bitsandbytes==0.37.2 does NOT solve the problem.

**Comment by twelveand0** [comment]
The problem still happened when i changed bitsandbytes to v0.37.2

**Comment by wanderingweights** [comment]
I agree; same problem here even with v0.37.2

**Comment by jonataslaw** [comment]
I solve my problem adding theses variables to .bashrc

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

remember to use `source .bashrc` after.

**Comment by pmudgal-Intel** [comment]
Changing bitsandbytes==0.37.2 fixed the problem for me. I had bitsandbytes==0.39.0 earlier.
